# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 66d52fdc8d8e6994a837b7b0ee3dea298869b2f2ddf8228aac664854364e1e66493079682dda4fd9a93ce7a0446d361daf62ea788a00a6dd6906ed63bb2c431c

test:
  secret_key_base: d15ec39f1527e654d99aec08cfcb9d029b1cb8bd2e52111fc29c46618d50c6766a144856bb31bb3e9fbaa4bc344253f6428b77f610305116a8d79ab03677c829

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
